version: "3.7"

services:
  # Don't need a MQTT broker at the moment, so it's commented out
  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mosquitto
  #   restart: always
  #   ports:
  #     - "8883:8883"
  #     - "9001:9001"
  #   volumes:
  #     - ./containers/mosquitto/config:/mosquitto/config
  #     - ./containers/mosquitto/data:/mosquitto/data
  #     - ./containers/mosquitto/log:/mosquitto/log
  #     - ./containers/certificates:/mosquitto/config/certs:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   user: "1000:1000"

  # Example of node-red setup if needed
  # node-red:
  #   image: nodered/node-red
  #   container_name: node-red
  #   restart: always
  #   volumes:
  #     - ./containers/node-red:/data
  #     - ./containers/certificates:/etc/ssl/private:ro
  #     - /etc/localtime:/etc/localtime:ro

  #   ports:
  #     - "1880:1880"
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
      - 8554:8554 # RTSP
      - 5000:5000 # WEB-UI
    environment:
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./containers/homeassistant:/config
      - ./containers/certificates:/etc/ssl/private:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
